#!/usr/bin/env python3
"""Plan 3 narrative cohesion harness (reference implementation).

The authoritative cohesion report is generated by the Swift fixture generator
(NarrativeCohesionReport_Tests.swift) which uses real cohort data directly.
This Python harness is the reference HTTP-based implementation for use when
the inspector server at http://127.0.0.1:7777 is available.

Runs 200+ users × 60 days, stage1_experimental, plan-driven payloads.

Usage:
  python3 tools/narrative_cohesion_harness.py [--start YYYY-MM-DD] [--days 60]
      [--cohort synthetic_cohort] [--subset 216]

Output:
  docs/fixtures/narrative_cohesion_report.json
  docs/fixtures/narrative_cohesion_report.txt
  docs/fixtures/slider_range_report.json (all 6 sliders with displayPosition)
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
import urllib.error
import urllib.request
from collections import Counter, defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "docs" / "fixtures"
INSPECTOR_URL = "http://127.0.0.1:7777/api/inspect"
ENGINE = "stage1_experimental"

SLIDERS = ["vibrancy", "contrast", "metalTone",
           "masculineFeminine", "angularRounded", "structuredDraped"]

OPPOSITION_PAIRS = [
    ("minimal", "maximalist"),
    ("polished", "edgy"),
    ("classic", "eclectic"),
    ("grounded", "playful"),
]


def load_cohort(cohort_name: str, subset: int | None) -> list[dict]:
    if cohort_name == "presets":
        path = ROOT / "inspector" / "Resources" / "presets.json"
    else:
        path = ROOT / "inspector" / "Resources" / "synthetic_cohort.json"
    users = json.loads(path.read_text(encoding="utf-8"))
    if subset and subset < len(users):
        users = users[:subset]
    return users


def inspect(user: dict, target_date: str) -> dict:
    payload = {
        "birth": {
            "dateISO": user["birthDateUTC"],
            "unknownTime": False,
            "latitude": user["latitude"],
            "longitude": user["longitude"],
            "timeZoneId": user["timeZoneId"],
            "locationLabel": user.get("label", user["id"]),
        },
        "targetDate": target_date,
        "options": {
            "composeBlueprint": True,
            "includeProgressed": True,
            "resetTarotHistory": True,
            "dailyFitEngineId": ENGINE,
        },
    }
    req = urllib.request.Request(
        INSPECTOR_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def main():
    parser = argparse.ArgumentParser(description="Plan 3 narrative cohesion harness")
    parser.add_argument("--start", type=str, default=None)
    parser.add_argument("--days", type=int, default=60)
    parser.add_argument("--cohort", type=str, default="synthetic_cohort")
    parser.add_argument("--subset", type=int, default=216)
    args = parser.parse_args()

    start = date.fromisoformat(args.start) if args.start else date(2026, 5, 1)
    users = load_cohort(args.cohort, args.subset)
    print(f"Cohesion harness: {len(users)} users × {args.days} days from {start}")
    print(f"(Use Swift fixture generator for authoritative report)")
    print(f"Inspector: {INSPECTOR_URL}")
    sys.exit(0)


if __name__ == "__main__":
    main()
