//
//  SemanticTokenGenerator.swift
//  Cosmic Fit
//
//  Created by Ashley Davison on 12/05/2025.
//  Enhanced with source tracking, improved weighting, and colour handling
//  Refactored to use InterpretationTextLibrary

/**
 * Style Guide and Colour Frequency token generation.
 * Daily Fit tokens are generated by DailyEnergyEngine.
 */

import Foundation

class SemanticTokenGenerator {
    
    // MARK: - Style Guide Specific Token Generation
    
    /// Generate Style Guide tokens with enhanced but balanced Venus/Mars/Moon priority
    static func generateStyleGuideTokens(natal: NatalChartCalculator.NatalChart, currentAge: Int = 30) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Get chart ruler for dominant influence
        let chartRuler = getChartRuler(ascendantSign: CoordinateTransformations.decimalDegreesToZodiac(natal.ascendant).sign)
        
        // Process planets with enhanced weighting for Venus, Mars, Moon + Chart Ruler dominance
        for planet in natal.planets {
            // Professional base weights with proper hierarchy
            let baseWeight: Double
            var priorityMultiplier: Double = 1.0
            
            // Chart ruler gets significant multiplier but Venus retains fashion dominance
            var chartRulerMultiplier: Double = 1.0
            if planet.name == chartRuler {
                chartRulerMultiplier = 2.5  // Strong but not overwhelming
                DebugLogger.info("🔱 CHART RULER DOMINANCE: \(planet.name) receives 2.5x multiplier for personal expression")
            }
            
            switch planet.name {
            case "Venus":
                baseWeight = 4.0 // Maximum for fashion authority
                priorityMultiplier = 2.0 // Venus dominates fashion choices
                // Final: 4.0 × 2.0 × chart_ruler × natal_weight = Venus fashion authority
            case "Mars":
                baseWeight = 2.2 // Strong but secondary to Venus for fashion
                priorityMultiplier = 1.3 // Energy expression role
                // Final: 2.2 × 1.3 × chart_ruler × natal_weight = Mars energy expression
            case "Moon":
                baseWeight = 2.5 // Strong for emotional comfort
                priorityMultiplier = 1.5 // Enhanced for emotional style preferences
                // Final: 2.5 × 1.5 × chart_ruler × natal_weight = Moon emotional resonance
            case "Sun":
                baseWeight = 2.0 // Core identity
                priorityMultiplier = 1.2 // Self-expression
            case "Mercury":
                baseWeight = 1.5 // Communication style
                priorityMultiplier = 0.9 // Supporting role
            case "Jupiter":
                baseWeight = 1.4 // Expansion and growth
                priorityMultiplier = 0.8 // Supporting role
            case "Saturn":
                baseWeight = 1.6 // Structure and discipline
                priorityMultiplier = 1.0 // Practical grounding
            case "Uranus", "Neptune", "Pluto":
                baseWeight = 1.3 // Transformative but background
                priorityMultiplier = 0.6 // Subtle influence
            default:
                baseWeight = 1.0 // Minor points
                priorityMultiplier = 0.3 // Minimal influence
            }
            
            // Apply WeightingModel natal weight with chart ruler dominance
            let weight = baseWeight * priorityMultiplier * chartRulerMultiplier * WeightingModel.natalWeight
            
            // Generate tokens using existing InterpretationTextLibrary
            let planetTokens = tokenizeForPlanetInSign(
                planet: planet.name,
                sign: planet.zodiacSign,
                isRetrograde: planet.isRetrograde,
                weight: weight
            )
            
            // For Venus, Mars, Moon - more moderate boost for specific token types
            let enhancedTokens = planetTokens.map { token in
                var enhancedWeight = token.weight
                
                if planet.name == "Venus" && (token.type == "colour" || token.type == "colour_quality") {
                    enhancedWeight *= 2.0 // Enhanced for Venus fashion authority
                } else if planet.name == "Mars" && (token.type == "structure" || token.type == "expression") {
                    enhancedWeight *= 1.3 // Mars energy expression enhancement
                } else if planet.name == "Moon" && (token.type == "texture" || token.type == "mood") {
                    enhancedWeight *= 1.5 // Enhanced for Moon emotional comfort priority
                }
                
                return StyleToken(
                    name: token.name,
                    type: token.type,
                    weight: enhancedWeight,
                    planetarySource: token.planetarySource,
                    signSource: token.signSource,
                    houseSource: token.houseSource,
                    aspectSource: token.aspectSource,
                    originType: token.originType
                )
            }
            
            // Apply age-dependent weighting
            let ageWeightedTokens = enhancedTokens.map { $0.applyingAgeWeight(currentAge: currentAge) }
            tokens.append(contentsOf: ageWeightedTokens)
        }
        
        // Process ascendant with reduced weight
        let ascendantSign = CoordinateTransformations.decimalDegreesToZodiac(natal.ascendant).sign
        
        print("✅ Ascendant tokens generated for sign: \(CoordinateTransformations.getZodiacSignName(sign: ascendantSign))")
        
        let ascendantTokens = tokenizeForPlanetInSign(
            planet: "Ascendant",
            sign: ascendantSign,
            isRetrograde: false,
            weight: 1.8 * WeightingModel.natalWeight) // Reduced from 2.5
        
        let ageWeightedAscTokens = ascendantTokens.map { $0.applyingAgeWeight(currentAge: currentAge) }
        tokens.append(contentsOf: ageWeightedAscTokens)
        
        // Add house cusps with reduced weight
        let houseCuspTokens = generateHouseCuspTokens(chart: natal, weight: WeightingModel.natalWeight * 0.7) // Reduced by 30%
        tokens.append(contentsOf: houseCuspTokens)
        
        // Process aspects with reduced weight
        let aspectTokens = generateAspectTokens(chart: natal, baseWeight: WeightingModel.natalWeight * 0.8) // Reduced by 20%
        tokens.append(contentsOf: aspectTokens)
        
        // Add Colour Season tokens for consistent fashion guidance (Partner's Feature)
        let colourSeason = ColourSeasonAnalyzer.determineColourSeason(chart: natal)
        let seasonalTokens = ColourSeasonAnalyzer.getSeasonalPalette(season: colourSeason)
        tokens.append(contentsOf: seasonalTokens)
        
        DebugLogger.info("🎨 COLOUR SEASON ANALYSIS: \(colourSeason.rawValue) with \(seasonalTokens.count) palette tokens")
        
        // Add expanded textile tokens for Daily System
        let textileTokens = generateExpandedTextileTokens(chart: natal)
        tokens.append(contentsOf: textileTokens)
        
        // Add pattern tokens for Daily System
        let patternTokens = generatePatternTokens(chart: natal)
        tokens.append(contentsOf: patternTokens)
        
        // Add accessory tokens for Daily System
        let accessoryTokens = generateAccessoryTokens(chart: natal)
        tokens.append(contentsOf: accessoryTokens)
        
        // Add debug logging for Venus/Mars/Moon dominance
        DebugLogger.info("🌟 BALANCED EXPRESSION PLANET WEIGHTS:")
        let venusTokens = tokens.filter { $0.planetarySource == "Venus" }
        let marsTokens = tokens.filter { $0.planetarySource == "Mars" }
        let moonTokens = tokens.filter { $0.planetarySource == "Moon" }
        
        DebugLogger.info("  • Venus: \(venusTokens.count) tokens, max weight: \(String(format: "%.2f", venusTokens.max(by: { $0.weight < $1.weight })?.weight ?? 0))")
        DebugLogger.info("  • Mars: \(marsTokens.count) tokens, max weight: \(String(format: "%.2f", marsTokens.max(by: { $0.weight < $1.weight })?.weight ?? 0))")
        DebugLogger.info("  • Moon: \(moonTokens.count) tokens, max weight: \(String(format: "%.2f", moonTokens.max(by: { $0.weight < $1.weight })?.weight ?? 0))")
        
        // ════════════════════════════════════════════════════════════════════════════════
        // NOTE: Tier 2 Token Generation (REMOVED)
        // ────────────────────────────────────────────────────────────────────────────────
        // Previously, this function generated "Tier 2 Applied Style Tokens" that mapped
        // energetic tokens to specific fashion descriptors (e.g., "fluid" → "bias_cut").
        //
        // ARCHITECTURAL DECISION (Dec 2025):
        // Both Style Guide and Daily Fit now use PRE-WRITTEN TEMPLATES selected based on
        // Tier 1 token patterns, rather than dynamic generation from Tier 2 tokens.
        //
        // STYLE GUIDE: Pre-written paragraphs selected via pattern matching on Tier 1
        // DAILY FIT: Static paragraphs attached to Tarot cards (78 cards × 3 versions)
        //
        // Tier 1 tokens are sufficient for:
        // • Vibe Breakdown generation (6 energies)
        // • Tarot card selection
        // • Color palette selection (DailyColourPaletteGenerator)
        // • Template selection (pattern matching)
        //
        // See Tier2TokenLibrary.swift for the unused implementation (kept for reference).
        // ════════════════════════════════════════════════════════════════════════════════
        
        return tokens
    }

    // MARK: - Colour Frequency Token Generation
    
    /// Generate tokens for Colour Frequency section using WeightingModel weights
    static func generateColourFrequencyTokens(
        natal: NatalChartCalculator.NatalChart,
        progressed: NatalChartCalculator.NatalChart,
        currentAge: Int = 30) -> [StyleToken] {
            
            var tokens: [StyleToken] = []
            
            // Normalized weights for natal vs progressed (natal + progressed = 0.70 total)
            let totalWeight = WeightingModel.natalWeight + WeightingModel.progressedWeight
            let normalizedNatalWeight = WeightingModel.natalWeight / totalWeight
            let normalizedProgressedWeight = WeightingModel.progressedWeight / totalWeight
            
            // Generate natal tokens with normalized weight
            let natalTokens = generateNatalColourTokens(natal, currentAge: currentAge)
            for token in natalTokens {
                let adjustedToken = StyleToken(
                    name: token.name,
                    type: token.type,
                    weight: token.weight * normalizedNatalWeight,
                    planetarySource: token.planetarySource,
                    signSource: token.signSource,
                    houseSource: token.houseSource,
                    aspectSource: token.aspectSource,
                    originType: .natal
                )
                tokens.append(adjustedToken)
            }
            
            // Generate progressed tokens with normalized weight
            let progressedTokens = generateProgressedColourTokens(progressed)
            for token in progressedTokens {
                // Skip tokens that introduce new colours - only keep modulating tokens
                if token.type == "colour" {
                    continue
                }
                
                // Keep only tokens that modulate finish, tone, and pairing logic
                if ["texture", "colour_quality", "structure"].contains(token.type) {
                    let adjustedToken = StyleToken(
                        name: token.name,
                        type: token.type,
                        weight: token.weight * normalizedProgressedWeight,
                        planetarySource: token.planetarySource,
                        signSource: token.signSource,
                        houseSource: token.houseSource,
                        aspectSource: token.aspectSource,
                        originType: .progressed
                    )
                    tokens.append(adjustedToken)
                }
            }
            
            return tokens
        }

    // MARK: - Helper Methods
    
    /// Generate tokens for a planet in a specific sign with source tracking
    static func tokenizeForPlanetInSign(
        planet: String,
        sign: Int,
        isRetrograde: Bool,
        weight: Double,
        isProgressed: Bool = false) -> [StyleToken] {
            
            var tokens: [StyleToken] = []
            
            // Get zodiac sign name
            let signName = CoordinateTransformations.getZodiacSignName(sign: sign)
            let planetSource = isProgressed ? "Progressed \(planet)" : planet
            let originType: OriginType = isProgressed ? .progressed : .natal
            
            // Generate tokens based on planet and sign using library
            if let planetDescriptions = getPlanetSignDescriptions(planet: planet, signName: signName) {
                var currentWeight = weight
                for (tokenName, tokenType) in planetDescriptions {
                    tokens.append(StyleToken(
                        name: tokenName,
                        type: tokenType,
                        weight: currentWeight,
                        planetarySource: planetSource,
                        signSource: signName,
                        originType: originType
                    ))
                    currentWeight -= 0.1
                }
            } else {
                // Fallback to elemental tokens using library
                let elementalTokens = getElementalFallbackTokens(signName: signName)
                var currentWeight = weight * 0.8
                for (tokenName, tokenType) in elementalTokens {
                    tokens.append(StyleToken(
                        name: tokenName,
                        type: tokenType,
                        weight: currentWeight,
                        planetarySource: planetSource,
                        signSource: signName,
                        originType: originType
                    ))
                    currentWeight -= 0.1
                }
            }
            
            // Add retrograde tokens if applicable
            if isRetrograde {
                if let retrogradeTokens = getRetrogradeTokens(planet: planet) {
                    var retroWeight = weight * 0.6
                    for (tokenName, tokenType) in retrogradeTokens {
                        tokens.append(StyleToken(
                            name: tokenName,
                            type: tokenType,
                            weight: retroWeight,
                            planetarySource: planetSource,
                            signSource: signName,
                            aspectSource: "Retrograde",
                            originType: originType
                        ))
                        retroWeight -= 0.1
                    }
                }
            }
            
            // LIMIT TOKEN GENERATION to prevent natal dominance
            // Determine max tokens based on planet importance
            let maxTokens: Int
            switch planet {
            case "Venus", "Mars", "Moon":
                maxTokens = 4 // Expression planets get more tokens (priority planets)
            case "Sun":
                maxTokens = 3 // Core identity gets moderate tokens
            case "Mercury", "Ascendant":
                maxTokens = 3 // Communication/appearance planets
            case "Jupiter", "Saturn":
                maxTokens = 2 // Social planets get fewer tokens
            case "Uranus", "Neptune", "Pluto":
                maxTokens = 1 // Outer planets get minimal tokens
            case let p where p.contains("Progressed"):
                // Progressed planets get limited tokens
                if p.contains("Moon") {
                    maxTokens = 3 // Progressed Moon is important
                } else {
                    maxTokens = 2 // Other progressed planets
                }
            default:
                maxTokens = 1 // Any other celestial bodies (Chiron, etc.)
            }
            
            // Sort tokens by weight (highest first) and limit to maxTokens
            tokens = tokens.sorted { $0.weight > $1.weight }
            
            // Apply the limit
            if tokens.count > maxTokens {
                tokens = Array(tokens.prefix(maxTokens))
                
                // Debug logging for token limiting
                DebugLogger.info("  ⚠️ Token limiting applied for \(planet): \(tokens.count) tokens (was unlimited)")
            }
            
            return tokens
        }
    
    /// Generate specialized colour tokens from natal chart
    private static func generateNatalColourTokens(_ chart: NatalChartCalculator.NatalChart, currentAge: Int = 30) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Process planets with focus on colour attributes
        for planet in chart.planets {
            let baseWeight: Double = 2.0
            var priorityMultiplier: Double = 1.0
            
            switch planet.name {
            case "Venus": priorityMultiplier = 1.6
            case "Moon": priorityMultiplier = 1.4
            case "Sun": priorityMultiplier = 1.2
            case "Mars": priorityMultiplier = 1.1
            case "Neptune": priorityMultiplier = 1.0
            default: priorityMultiplier = 0.8
            }
            
            let weight = baseWeight * priorityMultiplier
            
            let colourTokens = generateColourTokensForPlanetInSign(
                planet: planet.name,
                sign: planet.zodiacSign,
                weight: weight,
                isRetrograde: planet.isRetrograde)
            
            let ageWeightedTokens = colourTokens.map { $0.applyingAgeWeight(currentAge: currentAge) }
            tokens.append(contentsOf: ageWeightedTokens)
        }
        
        // Process ascendant for colour tokens
        let ascendantSign = CoordinateTransformations.decimalDegreesToZodiac(chart.ascendant).sign
        let ascSignName = CoordinateTransformations.getZodiacSignName(sign: ascendantSign)
        
        let ascendantColourTokens = generateColourTokensForAscendant(
            sign: ascendantSign,
            signName: ascSignName,
            weight: 2.5)
        
        let ageWeightedAscTokens = ascendantColourTokens.map { $0.applyingAgeWeight(currentAge: currentAge) }
        tokens.append(contentsOf: ageWeightedAscTokens)
        
        let elementalTokens = generateElementalColourTokens(chart: chart)
        tokens.append(contentsOf: elementalTokens)
        
        let aspectColourTokens = generateAspectColourTokens(chart: chart)
        tokens.append(contentsOf: aspectColourTokens)
        
        tokens.append(contentsOf: generateColourNuanceFromAspects(chart: chart))
        tokens.append(contentsOf: generateColourTokensFromDignities(chart: chart))
        
        return tokens
    }
    
    /// Generate colour tokens from progressed chart
    private static func generateProgressedColourTokens(_ chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        let relevantPlanets = ["Moon", "Venus", "Sun"]
        
        for planet in chart.planets where relevantPlanets.contains(planet.name) {
            let baseWeight: Double = 1.8
            
            var priorityMultiplier: Double = 1.0
            switch planet.name {
            case "Venus": priorityMultiplier = 1.5
            case "Moon": priorityMultiplier = 1.3
            case "Sun": priorityMultiplier = 1.2
            default: priorityMultiplier = 0.8
            }
            
            let weight = baseWeight * priorityMultiplier
            
            let colourTokens = generateColourTokensForPlanetInSign(
                planet: planet.name,
                sign: planet.zodiacSign,
                weight: weight,
                isProgressed: true)
            
            tokens.append(contentsOf: colourTokens)
        }
        
        tokens.append(StyleToken(
            name: "evolving",
            type: "colour_quality",
            weight: 1.5,
            planetarySource: "Progressed Chart",
            aspectSource: "Current Progression"
        ))
        
        tokens.append(StyleToken(
            name: "transitional",
            type: "colour_quality",
            weight: 1.3,
            planetarySource: "Progressed Chart",
            aspectSource: "Current Progression"
        ))
        
        return tokens
    }

    
    /// Generate tokens from house cusps based on the signs on each house cusp
    /// Uses Placidus house system for precise cusp calculations
    private static func generateHouseCuspTokens(chart: NatalChartCalculator.NatalChart, weight: Double) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Process each house cusp (1-12)
        for houseNumber in 1...12 {
            let cuspLongitude = chart.houseCusps[houseNumber]
            let cuspSign = Int(cuspLongitude / 30.0) % 12 + 1
            let signName = CoordinateTransformations.getZodiacSignName(sign: cuspSign)
            
            // Determine house type and base weight
            let houseType = getHouseType(houseNumber: houseNumber)
            let baseWeight = getHouseWeight(houseNumber: houseNumber, houseType: houseType) * weight
            
            // Generate tokens based on house significance and sign combination
            let houseTokens = generateTokensForHouseCusp(
                houseNumber: houseNumber,
                signName: signName,
                houseType: houseType,
                baseWeight: baseWeight
            )
            
            tokens.append(contentsOf: houseTokens)
            
            // Add angular house emphasis tokens for most important houses
            if houseType == .angular {
                let angularTokens = generateAngularHouseTokens(
                    houseNumber: houseNumber,
                    signName: signName,
                    weight: baseWeight * 0.8
                )
                tokens.append(contentsOf: angularTokens)
            }
        }
        
        return tokens
    }
    
    /// Determine the type of house (angular, succedent, cadent)
    private static func getHouseType(houseNumber: Int) -> HouseType {
        switch houseNumber {
        case 1, 4, 7, 10:    return .angular     // Most important - ASC, IC, DSC, MC
        case 2, 5, 8, 11:    return .succedent   // Fixed, stable energy
        case 3, 6, 9, 12:    return .cadent      // Mutable, transitional energy
        default:             return .cadent
        }
    }
    
    /// Calculate weight multiplier based on house importance
    private static func getHouseWeight(houseNumber: Int, houseType: HouseType) -> Double {
        switch houseType {
        case .angular:
            // Angular houses get highest weight, with 1st and 10th being most prominent
            switch houseNumber {
            case 1:  return 1.0    // Ascendant - identity and appearance
            case 10: return 0.9    // Midheaven - public image and reputation
            case 7:  return 0.8    // Descendant - partnerships and others' perception
            case 4:  return 0.7    // IC - roots and private self
            default: return 0.7
            }
        case .succedent:
            // Succedent houses moderate weight
            switch houseNumber {
            case 2:  return 0.6    // Values and resources - affects style choices
            case 5:  return 0.5    // Creativity and self-expression
            case 8:  return 0.4    // Transformation style
            case 11: return 0.4    // Groups and aspirations
            default: return 0.5
            }
        case .cadent:
            // Cadent houses lighter weight but still influential
            switch houseNumber {
            case 3:  return 0.4    // Communication style
            case 6:  return 0.5    // Daily routine and health - practical style
            case 9:  return 0.3    // Philosophy and expansion
            case 12: return 0.3    // Subconscious expression
            default: return 0.3
            }
        }
    }
    
    /// Generate specific tokens for a house cusp based on house meaning + sign combination
    private static func generateTokensForHouseCusp(
        houseNumber: Int,
        signName: String,
        houseType: HouseType,
        baseWeight: Double
    ) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Get house-specific style influence
        let houseInfluence = getHouseStyleInfluence(houseNumber: houseNumber)
        let signTokens = getSignTokensForHouse(signName: signName, houseNumber: houseNumber)
        
        // Combine house meaning with sign expression
        for (tokenName, tokenType) in signTokens {
            let adjustedWeight = baseWeight * getTokenTypeMultiplier(tokenType: tokenType, houseNumber: houseNumber)
            
            tokens.append(StyleToken(
                name: tokenName,
                type: tokenType,
                weight: adjustedWeight,
                signSource: signName,
                houseSource: houseNumber,
                originType: .natal
            ))
        }
        
        // Add house-specific structural tokens
        if let structuralToken = houseInfluence.structural {
            tokens.append(StyleToken(
                name: structuralToken,
                type: "structure",
                weight: baseWeight * 0.8,
                houseSource: houseNumber,
                originType: .natal
            ))
        }
        
        return tokens
    }
    
    /// Generate specialized tokens for angular houses (most visible influence)
    private static func generateAngularHouseTokens(
        houseNumber: Int,
        signName: String,
        weight: Double
    ) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        switch houseNumber {
        case 1: // Ascendant - Primary identity and first impressions
            tokens.append(StyleToken(
                name: "defining",
                type: "expression",
                weight: weight,
                signSource: signName,
                houseSource: 1,
                originType: .natal
            ))
            tokens.append(StyleToken(
                name: "visible",
                type: "structure",
                weight: weight * 0.9,
                signSource: signName,
                houseSource: 1,
                originType: .natal
            ))
            
        case 4: // IC - Private self and emotional foundation
            tokens.append(StyleToken(
                name: "foundational",
                type: "mood",
                weight: weight,
                signSource: signName,
                houseSource: 4,
                originType: .natal
            ))
            tokens.append(StyleToken(
                name: "comforting",
                type: "texture",
                weight: weight * 0.8,
                signSource: signName,
                houseSource: 4,
                originType: .natal
            ))
            
        case 7: // Descendant - Partnerships and social presentation
            tokens.append(StyleToken(
                name: "harmonious",
                type: "expression",
                weight: weight,
                signSource: signName,
                houseSource: 7,
                originType: .natal
            ))
            tokens.append(StyleToken(
                name: "balanced",
                type: "structure",
                weight: weight * 0.8,
                signSource: signName,
                houseSource: 7,
                originType: .natal
            ))
            
        case 10: // Midheaven - Public image and professional presentation
            tokens.append(StyleToken(
                name: "authoritative",
                type: "expression",
                weight: weight,
                signSource: signName,
                houseSource: 10,
                originType: .natal
            ))
            tokens.append(StyleToken(
                name: "polished",
                type: "texture",
                weight: weight * 0.9,
                signSource: signName,
                houseSource: 10,
                originType: .natal
            ))
            
        default:
            break
        }
        
        return tokens
    }

    // MARK: - Colour Season System (Partner's Feature Request)
    
    /// Professional colour season analysis based on astrological chart
    enum ColourSeason: String, CaseIterable {
        case brightSpring = "Bright Spring"
        case lightSpring = "Light Spring" 
        case warmSpring = "Warm Spring"
        case brightSummer = "Bright Summer"
        case lightSummer = "Light Summer"
        case coolSummer = "Cool Summer"
        case brightAutumn = "Bright Autumn"
        case warmAutumn = "Warm Autumn"
        case deepAutumn = "Deep Autumn"
        case brightWinter = "Bright Winter"
        case coolWinter = "Cool Winter"
        case deepWinter = "Deep Winter"
    }
    
    /// Colour Season Analyzer for professional fashion guidance
    struct ColourSeasonAnalyzer {
        
        /// Determine colour season based on astrological chart factors
        static func determineColourSeason(chart: NatalChartCalculator.NatalChart) -> ColourSeason {
            // Analyze elemental balance for warmth/coolness
            let fireCount = countFirePlacements(chart: chart)
            let earthCount = countEarthPlacements(chart: chart)
            let airCount = countAirPlacements(chart: chart)
            let waterCount = countWaterPlacements(chart: chart)
            
            // Determine undertone (warm vs cool)
            let isWarmUndertone = (fireCount + earthCount) > (airCount + waterCount)
            
            // Determine intensity (bright vs muted vs deep)
            let venusIntensity = calculateVenusIntensity(chart: chart)
            
            // Determine lightness (light vs deep)
            let isLightExpression = hasLightExpression(chart: chart)
            
            // Professional colour season determination (fixed redundant cases)
            switch (isWarmUndertone, venusIntensity, isLightExpression) {
            case (true, .bright, true): return .brightSpring
            case (true, .muted, true): return .lightSpring
            case (true, .bright, false): return .warmSpring
            case (true, .muted, false): return .warmAutumn
            case (true, .deep, false): return .deepAutumn
            case (false, .bright, true): return .brightSummer
            case (false, .muted, true): return .lightSummer
            case (false, .muted, false): return .coolSummer
            case (false, .bright, false): return .brightWinter
            case (false, .deep, false): return .deepWinter
            default: return .deepAutumn // Fallback
            }
        }
        
        /// Get seasonal colour palette for consistent fashion guidance
        static func getSeasonalPalette(season: ColourSeason) -> [StyleToken] {
            let baseColours = seasonalColourMappings[season] ?? []
            return baseColours.map { (colourName, intensity) in
                StyleToken(
                    name: colourName,
                    type: "colour",
                    weight: intensity,
                    planetarySource: "ColourSeason",
                    aspectSource: "Colour Season: \(season.rawValue)",
                    originType: .natal
                )
            }
        }
        
        /// Modulate daily intensity while maintaining seasonal coherence
        static func modulateForDaily(palette: [StyleToken], transits: [Any]) -> [StyleToken] {
            // Maintain palette but adjust intensity based on daily transits
            return palette.map { token in
                let dailyIntensity = calculateDailyIntensityModulation(transits: transits)
                return token.withWeight(token.weight * dailyIntensity)
            }
        }
        
        // MARK: - Helper Methods
        
        private enum VenusIntensity {
            case bright, muted, deep
        }
        
        private static let seasonalColourMappings: [ColourSeason: [(String, Double)]] = [
            .deepAutumn: [("rust", 2.0), ("olive", 1.8), ("burgundy", 1.9), ("golden brown", 1.7), ("deep orange", 1.6)],
            .brightWinter: [("royal blue", 2.0), ("emerald", 1.9), ("magenta", 1.8), ("black", 2.0), ("white", 1.7)],
            .warmSpring: [("coral", 1.8), ("golden yellow", 1.9), ("warm green", 1.6), ("peach", 1.7), ("camel", 1.5)],
            .coolSummer: [("lavender", 1.6), ("soft blue", 1.7), ("rose", 1.5), ("mint", 1.4), ("pearl gray", 1.6)]
            // Add more seasonal mappings as needed
        ]
        

        
        private static func countFirePlacements(chart: NatalChartCalculator.NatalChart) -> Int {
            return chart.planets.filter { [1, 5, 9].contains($0.zodiacSign) }.count
        }
        
        private static func countEarthPlacements(chart: NatalChartCalculator.NatalChart) -> Int {
            return chart.planets.filter { [2, 6, 10].contains($0.zodiacSign) }.count
        }
        
        private static func countAirPlacements(chart: NatalChartCalculator.NatalChart) -> Int {
            return chart.planets.filter { [3, 7, 11].contains($0.zodiacSign) }.count
        }
        
        private static func countWaterPlacements(chart: NatalChartCalculator.NatalChart) -> Int {
            return chart.planets.filter { [4, 8, 12].contains($0.zodiacSign) }.count
        }
        
        private static func calculateVenusIntensity(chart: NatalChartCalculator.NatalChart) -> VenusIntensity {
            guard let venus = chart.planets.first(where: { $0.name == "Venus" }) else { return .muted }
            
            // Fire/Mars aspects = bright, Earth/Saturn = deep, Water/Air = muted
            switch venus.zodiacSign {
            case 1, 5, 9: return .bright  // Fire signs
            case 2, 6, 10: return .deep   // Earth signs  
            default: return .muted        // Air/Water signs
            }
        }
        
        private static func hasLightExpression(chart: NatalChartCalculator.NatalChart) -> Bool {
            // Light expression = more air/fire, fewer planets in deep signs
            let lightSigns = [1, 3, 5, 7, 9, 11] // Fire and Air
            let lightPlacements = chart.planets.filter { lightSigns.contains($0.zodiacSign) }.count
            return lightPlacements > 3
        }
        
        private static func calculateDailyIntensityModulation(transits: [Any]) -> Double {
            // Placeholder for daily transit intensity calculation
            return 1.0 + (Double.random(in: -0.2...0.2)) // ±20% daily variation
        }
    }

    // MARK: - Traditional Astrological Colour Correspondences
    
    /// Traditional astrological colour mappings per professional standards
    struct TraditionalColours {
        static let signColours: [String: [(String, String)]] = [
            "Aries": [("red", "colour"), ("bright orange", "colour"), ("bold contrast", "colour_quality")],
            "Taurus": [("sage green", "colour"), ("rose", "colour"), ("warm brown", "colour"), ("cream", "colour")],
            "Gemini": [("yellow", "colour"), ("bright patterns", "colour_quality"), ("mixed combinations", "colour_quality")],
            "Cancer": [("white", "colour"), ("silver", "colour"), ("pearl", "colour"), ("nautical themes", "colour_quality")],
            "Leo": [("gold", "colour"), ("orange", "colour"), ("red", "colour"), ("purple", "colour"), ("crimson", "colour"), ("royal", "colour_quality")],
            "Virgo": [("navy", "colour"), ("wheat", "colour"), ("brown", "colour"), ("precisely tailored", "colour_quality")],
            "Libra": [("rose pink", "colour"), ("pastels", "colour"), ("harmonious combinations", "colour_quality"), ("balanced proportions", "colour_quality")],
            "Scorpio": [("black", "colour"), ("burgundy", "colour"), ("deep colours", "colour_quality"), ("power silhouettes", "colour_quality")],
            "Sagittarius": [("purple", "colour"), ("royal blue", "colour"), ("international influences", "colour_quality"), ("travel ready", "colour_quality")],
            "Capricorn": [("charcoal", "colour"), ("brown", "colour"), ("black", "colour"), ("classic business", "colour_quality")],
            "Aquarius": [("electric blue", "colour"), ("unexpected combinations", "colour_quality"), ("technical fabrics", "colour_quality")],
            "Pisces": [("sea colours", "colour_quality"), ("flowing fabrics", "colour_quality"), ("ethereal elements", "colour_quality")]
        ]
    }
    
    /// Enhanced traditional token generation with professional astrological accuracy
    private static func generateTraditionalSignTokens(signName: String) -> [(String, String)] {
        return TraditionalColours.signColours[signName] ?? [("neutral", "colour")]
    }
    
    /// Get chart ruler (ruling planet of Ascendant) for dominant personal expression
    private static func getChartRuler(ascendantSign: Int) -> String {
        switch ascendantSign {
        case 1: return "Mars"      // Aries
        case 2: return "Venus"     // Taurus
        case 3: return "Mercury"   // Gemini
        case 4: return "Moon"      // Cancer
        case 5: return "Sun"       // Leo
        case 6: return "Mercury"   // Virgo
        case 7: return "Venus"     // Libra
        case 8: return "Mars"      // Scorpio (traditional ruler)
        case 9: return "Jupiter"   // Sagittarius
        case 10: return "Saturn"   // Capricorn
        case 11: return "Saturn"   // Aquarius (traditional ruler)
        case 12: return "Jupiter"  // Pisces (traditional ruler)
        default: return "Sun"      // Fallback
        }
    }
    
    /// Professional aggressive orb-based weighting for precise astrological accuracy
    private static func calculateProfessionalOrbMultiplier(orb: Double) -> Double {
        switch orb {
        case 0.0..<1.0:
            return 2.0    // Exact aspects (like 0.11°) = 100% strength × 2x multiplier
        case 1.0..<2.0:
            return 1.5    // Tight aspects = 80% strength × 1.5x multiplier  
        case 2.0..<3.0:
            return 1.0    // Normal aspects = 50% strength × 1x multiplier
        case 3.0..<4.0:
            return 0.7    // Wide aspects = 30% strength × 0.7x multiplier
        default:
            return 0.3    // Very wide aspects = 20% strength × 0.3x multiplier
        }
    }
    
    // MARK: - Professional Astrological Validation
    
    /// Validation warnings for astrological accuracy
    enum ValidationWarning {
        case venusUnderwhelming
        case dailyVariationExcessive
        case natalInfluenceTooLow
        case traditionalColourMismatch
        case aspectMeaningMissing
    }
    
    /// Professional astrological validation system
    struct AstrologicalValidation {
        
        /// Validate token mappings against professional astrological standards
        static func validateTokenMappings(tokens: [StyleToken], chart: NatalChartCalculator.NatalChart) -> [ValidationWarning] {
            var warnings: [ValidationWarning] = []
            
            // Check Venus dominance for fashion
            let venusTokens = tokens.filter { $0.planetarySource == "Venus" }
            let totalWeight = tokens.reduce(0) { $0 + $1.weight }
            let venusPercentage = venusTokens.reduce(0) { $0 + $1.weight } / totalWeight
            
            if venusPercentage < 0.3 {
                warnings.append(.venusUnderwhelming)
            }
            
            // Check daily variation target
            let natalTokens = tokens.filter { $0.originType == .natal }
            let dailyTokens = tokens.filter { [.transit, .weather, .phase].contains($0.originType) }
            let natalPercentage = natalTokens.reduce(0) { $0 + $1.weight } / totalWeight
            let dailyPercentage = dailyTokens.reduce(0) { $0 + $1.weight } / totalWeight
            
            if natalPercentage < 0.45 {
                warnings.append(.natalInfluenceTooLow)
            }
            
            if dailyPercentage > 0.25 {
                warnings.append(.dailyVariationExcessive)
            }
            
            return warnings
        }
        
        /// Validate traditional sign-colour alignment
        static func validateTraditionalAlignment(tokens: [StyleToken]) -> Bool {
            // Check that traditional colour mappings are being used
            let taurusTokens = tokens.filter { $0.signSource == "Taurus" }
            let hasTraditionalTaurusColours = taurusTokens.contains { token in
                ["sage green", "rose", "warm brown", "cream"].contains(token.name)
            }
            
            let scorpioTokens = tokens.filter { $0.signSource == "Scorpio" }
            let hasTraditionalScorpioElements = scorpioTokens.contains { token in
                ["black", "burgundy", "leather", "power", "magnetic"].contains(token.name)
            }
            
            return hasTraditionalTaurusColours && hasTraditionalScorpioElements
        }
    }

    /// Get sign-specific tokens modified by house context
    private static func getSignTokensForHouse(signName: String, houseNumber: Int) -> [(String, String)] {
        // Base sign tokens from interpretation library - use Sun sign descriptions as general baseline
        let baseSignTokens = InterpretationTextLibrary.TokenGeneration.PlanetInSign.Sun.descriptions[signName] ?? []
        
        // Filter and modify tokens based on house context
        var houseModifiedTokens: [(String, String)] = []
        
        for (tokenName, tokenType) in baseSignTokens {
            // Modify token based on house influence
            let modifiedToken = modifyTokenForHouseContext(
                tokenName: tokenName,
                tokenType: tokenType,
                houseNumber: houseNumber
            )
            houseModifiedTokens.append(modifiedToken)
        }
        
        return houseModifiedTokens
    }
    
    /// Modify tokens based on house context
    private static func modifyTokenForHouseContext(
        tokenName: String,
        tokenType: String,
        houseNumber: Int
    ) -> (String, String) {
        
        // House-specific modifications to make tokens more relevant
        switch houseNumber {
        case 1: // Identity house - emphasize expression
            if tokenType == "mood" { return (tokenName, "expression") }
        case 2: // Values house - emphasize texture and substance
            if tokenType == "expression" { return (tokenName, "texture") }
        case 6: // Service house - emphasize practical structure
            if tokenType == "colour_quality" { return ("practical-\(tokenName)", "structure") }
        case 10: // Career house - emphasize professional expression
            if tokenType == "mood" { return ("professional-\(tokenName)", "expression") }
        default:
            break
        }
        
        return (tokenName, tokenType)
    }
    
    /// Get house-specific style influences
    private static func getHouseStyleInfluence(houseNumber: Int) -> (structural: String?, expressive: String?) {
        switch houseNumber {
        case 1:  return (structural: "prominent", expressive: "defining")
        case 2:  return (structural: "substantial", expressive: "tactile")
        case 3:  return (structural: "versatile", expressive: "communicative")
        case 4:  return (structural: "grounded", expressive: "nurturing")
        case 5:  return (structural: "expressive", expressive: "creative")
        case 6:  return (structural: "functional", expressive: "practical")
        case 7:  return (structural: "balanced", expressive: "harmonious")
        case 8:  return (structural: "transformative", expressive: "intense")
        case 9:  return (structural: "expansive", expressive: "worldly")
        case 10: return (structural: "structured", expressive: "authoritative")
        case 11: return (structural: "innovative", expressive: "unconventional")
        case 12: return (structural: "subtle", expressive: "mystical")
        default: return (structural: nil, expressive: nil)
        }
    }
    
    /// Adjust token weight based on type and house combination
    private static func getTokenTypeMultiplier(tokenType: String, houseNumber: Int) -> Double {
        switch houseNumber {
        case 1, 10: // Most visible houses
            switch tokenType {
            case "expression": return 1.2
            case "structure": return 1.1
            case "colour_quality": return 1.0
            default: return 0.9
            }
        case 2, 6: // Practical houses
            switch tokenType {
            case "texture": return 1.2
            case "structure": return 1.1
            default: return 1.0
            }
        case 4, 7: // Relationship houses
            switch tokenType {
            case "mood": return 1.1
            case "expression": return 1.0
            default: return 0.9
            }
        default:
            return 1.0
        }
    }
    
    /// House type enumeration
    private enum HouseType {
        case angular    // 1, 4, 7, 10 - Most active and prominent
        case succedent  // 2, 5, 8, 11 - Fixed and stable
        case cadent     // 3, 6, 9, 12 - Mutable and transitional
    }
    
    /// Enhanced aspect token generation with professional astrological meaning
    private static func generateAspectTokens(chart: NatalChartCalculator.NatalChart, baseWeight: Double) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        for i in 0..<chart.planets.count {
            let planet1 = chart.planets[i]
            for j in (i+1)..<chart.planets.count {
                let planet2 = chart.planets[j]
                
                if let (aspectType, orb) = AstronomicalCalculator.calculateAspect(
                    point1: planet1.longitude,
                    point2: planet2.longitude,
                    orb: 5.0) {
                    
                    let aspectSource = "\(planet1.name) \(aspectType) \(planet2.name)"
                    var aspectWeight = baseWeight * 2.0
                    
                    // Professional aggressive orb-based weighting
                    let orbMultiplier = calculateProfessionalOrbMultiplier(orb: orb)
                    aspectWeight *= orbMultiplier
                    
                    // Generate aspect-specific tokens with professional meanings
                    let aspectSpecificTokens = generateAspectSpecificTokens(
                        planet1: planet1.name,
                        planet2: planet2.name,
                        aspectType: aspectType,
                        baseWeight: aspectWeight
                    )
                    
                    for aspectToken in aspectSpecificTokens {
                        tokens.append(StyleToken(
                            name: aspectToken.name,
                            type: aspectToken.type,
                            weight: aspectToken.weight,
                            planetarySource: "\(planet1.name)-\(planet2.name)",
                            aspectSource: aspectSource,
                            originType: .natal
                        ))
                    }
                }
            }
        }
        
        return tokens
    }
    
    /// Professional aspect-specific token generation based on astrological meaning
    private static func generateAspectSpecificTokens(
        planet1: String,
        planet2: String,
        aspectType: String,
        baseWeight: Double
    ) -> [(name: String, type: String, weight: Double)] {
        
        // Focus on Venus aspects for fashion authority
        if (planet1 == "Venus" || planet2 == "Venus") {
            let otherPlanet = planet1 == "Venus" ? planet2 : planet1
            return generateVenusAspectTokens(otherPlanet: otherPlanet, aspectType: aspectType, baseWeight: baseWeight)
        }
        
        // Focus on Moon aspects for emotional comfort
        if (planet1 == "Moon" || planet2 == "Moon") {
            let otherPlanet = planet1 == "Moon" ? planet2 : planet1
            return generateMoonAspectTokens(otherPlanet: otherPlanet, aspectType: aspectType, baseWeight: baseWeight)
        }
        
        // Focus on Mars aspects for energy expression
        if (planet1 == "Mars" || planet2 == "Mars") {
            let otherPlanet = planet1 == "Mars" ? planet2 : planet1
            return generateMarsAspectTokens(otherPlanet: otherPlanet, aspectType: aspectType, baseWeight: baseWeight)
        }
        
        // Default generic aspect token
        return [(name: getAspectMoodToken(aspectType: aspectType), type: "mood", weight: baseWeight)]
    }
    
    /// Venus aspect tokens with professional fashion implications
    private static func generateVenusAspectTokens(otherPlanet: String, aspectType: String, baseWeight: Double) -> [(name: String, type: String, weight: Double)] {
        switch (otherPlanet, aspectType) {
        case ("Moon", "Trine"):
            return [("effortless_beauty", "expression", baseWeight * 1.5), ("comfortable_luxury", "texture", baseWeight)]
        case ("Moon", "Square"):
            return [("polished_comfort", "approach", baseWeight), ("strategic_softness", "texture", baseWeight)]
        case ("Moon", "Opposition"):
            return [("sophisticated_comfort", "approach", baseWeight), ("public_private_balance", "structure", baseWeight)]
        case ("Mars", "Trine"):
            return [("confident_sensuality", "expression", baseWeight * 1.3), ("dynamic_beauty", "mood", baseWeight)]
        case ("Mars", "Square"):
            return [("tension_resolution", "approach", baseWeight), ("bold_refinement", "expression", baseWeight)]
        case ("Jupiter", "Trine"):
            return [("abundant_style", "approach", baseWeight), ("generous_beauty", "expression", baseWeight)]
        case ("Saturn", "Trine"):
            return [("timeless_elegance", "approach", baseWeight * 1.2), ("structured_beauty", "structure", baseWeight)]
        case ("Saturn", "Square"):
            return [("refined_discipline", "approach", baseWeight), ("earned_elegance", "expression", baseWeight)]
        default:
            return [(name: "harmonious", type: "mood", weight: baseWeight)]
        }
    }
    
    /// Moon aspect tokens with emotional comfort implications
    private static func generateMoonAspectTokens(otherPlanet: String, aspectType: String, baseWeight: Double) -> [(name: String, type: String, weight: Double)] {
        switch (otherPlanet, aspectType) {
        case ("Venus", _): // Handled in Venus aspects
            return []
        case ("Mars", "Trine"):
            return [("emotionally_dynamic", "expression", baseWeight), ("protective_strength", "structure", baseWeight)]
        case ("Mars", "Square"):
            return [("emotional_armor", "structure", baseWeight), ("defensive_style", "approach", baseWeight)]
        case ("Saturn", "Trine"):
            return [("emotional_security", "approach", baseWeight), ("stable_comfort", "texture", baseWeight)]
        default:
            return [(name: "emotionally_responsive", type: "mood", weight: baseWeight)]
        }
    }
    
    /// Mars aspect tokens with energy expression implications
    private static func generateMarsAspectTokens(otherPlanet: String, aspectType: String, baseWeight: Double) -> [(name: String, type: String, weight: Double)] {
        switch (otherPlanet, aspectType) {
        case ("Venus", _), ("Moon", _): // Handled in other aspect functions
            return []
        case ("Jupiter", "Trine"):
            return [("expansive_energy", "expression", baseWeight), ("confident_action", "structure", baseWeight)]
        case ("Saturn", "Square"):
            return [("disciplined_energy", "approach", baseWeight), ("strategic_action", "structure", baseWeight)]
        case ("Uranus", "Trine"):
            return [("innovative_action", "expression", baseWeight), ("electric_energy", "mood", baseWeight)]
        default:
            return [(name: "energetic", type: "mood", weight: baseWeight)]
        }
    }
    

    
    private static func generateColourTokensForPlanetInSign(planet: String, sign: Int, weight: Double, isRetrograde: Bool = false, isProgressed: Bool = false) -> [StyleToken] {
        return []
    }
    
    private static func generateColourTokensForAscendant(sign: Int, signName: String, weight: Double) -> [StyleToken] {
        return []
    }
    
    private static func generateElementalColourTokens(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        return []
    }
    
    private static func generateAspectColourTokens(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        return []
    }
    
    private static func generateColourNuanceFromAspects(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        return []
    }
    
    private static func generateColourTokensFromDignities(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        return []
    }
    
    private static func getPlanetSignDescriptions(planet: String, signName: String) -> [(String, String)]? {
        switch planet {
        case "Sun":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Sun.descriptions[signName]
        case "Moon":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Moon.descriptions[signName]
        case "Venus":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Venus.descriptions[signName]
        case "Mars":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Mars.descriptions[signName]
        case "Mercury":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Mercury.descriptions[signName]
        case "Jupiter":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.OuterPlanets.jupiter
        case "Saturn":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.OuterPlanets.saturn
        case "Uranus":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.OuterPlanets.uranus
        case "Neptune":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.OuterPlanets.neptune
        case "Pluto":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.OuterPlanets.pluto
        default:
            return nil
        }
    }
    
    private static func getElementalFallbackTokens(signName: String) -> [(String, String)] {
        if ["Aries", "Leo", "Sagittarius"].contains(signName) {
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.ElementalFallbacks.fire
        } else if ["Taurus", "Virgo", "Capricorn"].contains(signName) {
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.ElementalFallbacks.earth
        } else if ["Gemini", "Libra", "Aquarius"].contains(signName) {
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.ElementalFallbacks.air
        } else if ["Cancer", "Scorpio", "Pisces"].contains(signName) {
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.ElementalFallbacks.water
        } else {
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.ElementalFallbacks.fire
        }
    }
    
    private static func getRetrogradeTokens(planet: String) -> [(String, String)]? {
        switch planet {
        case "Venus":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Retrograde.venus
        case "Mars":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Retrograde.mars
        case "Mercury":
            return InterpretationTextLibrary.TokenGeneration.PlanetInSign.Retrograde.mercury
        default:
            return nil
        }
    }
    
    private static func getAspectMoodToken(aspectType: String) -> String {
        switch aspectType {
        case "Conjunction", "Trine": return "harmonious"
        case "Square", "Opposition": return "dynamic"
        case "Sextile": return "supportive"
        default: return "subtle"
        }
    }
    

    // MARK: - Expanded Token Generation for Daily System
    
    /// Generate comprehensive textile tokens based on chart elements and planets
    static func generateExpandedTextileTokens(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Get dominant elements for textile guidance
        let elementWeights = calculateElementalWeights(chart: chart)
        let _ = elementWeights.max(by: { $0.value < $1.value })?.key ?? "balanced"
        
        // Venus-based textile preferences
        if let venus = chart.planets.first(where: { $0.name == "Venus" }) {
            let venusElement = getSignElement(sign: venus.zodiacSign)
            let venusModality = getSignModality(sign: venus.zodiacSign)
            
            switch venusElement {
            case "fire":
                tokens.append(StyleToken(name: "lightweight", type: "textile", weight: 1.2, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "breathable", type: "textile", weight: 1.0, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "energetic", type: "textile", weight: 0.8, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
            case "earth":
                tokens.append(StyleToken(name: "structured", type: "textile", weight: 1.3, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "textured", type: "textile", weight: 1.1, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "substantial", type: "textile", weight: 0.9, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
            case "air":
                tokens.append(StyleToken(name: "flowing", type: "textile", weight: 1.2, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "airy", type: "textile", weight: 1.0, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "versatile", type: "textile", weight: 0.8, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
            case "water":
                tokens.append(StyleToken(name: "soft", type: "textile", weight: 1.3, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "draping", type: "textile", weight: 1.1, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
                tokens.append(StyleToken(name: "fluid", type: "textile", weight: 0.9, planetarySource: "Venus", signSource: CoordinateTransformations.getZodiacSignName(sign: venus.zodiacSign), originType: .natal))
            default:
                tokens.append(StyleToken(name: "adaptable", type: "textile", weight: 1.0, planetarySource: "Venus", originType: .natal))
            }
            
            // Modality-based additions
            switch venusModality {
            case "cardinal":
                tokens.append(StyleToken(name: "crisp", type: "textile", weight: 0.8, planetarySource: "Venus", originType: .natal))
            case "fixed":
                tokens.append(StyleToken(name: "substantial", type: "textile", weight: 0.9, planetarySource: "Venus", originType: .natal))
            case "mutable":
                tokens.append(StyleToken(name: "adaptable", type: "textile", weight: 0.7, planetarySource: "Venus", originType: .natal))
            default:
                break
            }
        }
        
        // Mars-based energy textile preferences
        if let mars = chart.planets.first(where: { $0.name == "Mars" }) {
            let marsElement = getSignElement(sign: mars.zodiacSign)
            
            switch marsElement {
            case "fire":
                tokens.append(StyleToken(name: "dynamic", type: "textile", weight: 0.8, planetarySource: "Mars", originType: .natal))
            case "earth":
                tokens.append(StyleToken(name: "durable", type: "textile", weight: 0.7, planetarySource: "Mars", originType: .natal))
            case "air":
                tokens.append(StyleToken(name: "movement-friendly", type: "textile", weight: 0.6, planetarySource: "Mars", originType: .natal))
            case "water":
                tokens.append(StyleToken(name: "comfort-focused", type: "textile", weight: 0.7, planetarySource: "Mars", originType: .natal))
            default:
                break
            }
        }
        
        return tokens
    }
    
    /// Generate pattern tokens based on planetary and elemental influences
    static func generatePatternTokens(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Venus pattern preferences
        if let venus = chart.planets.first(where: { $0.name == "Venus" }) {
            let venusElement = getSignElement(sign: venus.zodiacSign)
            let venusModality = getSignModality(sign: venus.zodiacSign)
            
            switch venusElement {
            case "fire":
                tokens.append(StyleToken(name: "geometric", type: "pattern", weight: 1.0, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "angular", type: "pattern", weight: 0.8, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "bold", type: "pattern", weight: 0.7, planetarySource: "Venus", originType: .natal))
            case "earth":
                tokens.append(StyleToken(name: "organic", type: "pattern", weight: 1.1, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "natural", type: "pattern", weight: 0.9, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "textural", type: "pattern", weight: 0.8, planetarySource: "Venus", originType: .natal))
            case "air":
                tokens.append(StyleToken(name: "abstract", type: "pattern", weight: 1.0, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "scattered", type: "pattern", weight: 0.8, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "versatile", type: "pattern", weight: 0.7, planetarySource: "Venus", originType: .natal))
            case "water":
                tokens.append(StyleToken(name: "flowing", type: "pattern", weight: 1.1, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "soft-edged", type: "pattern", weight: 0.9, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "organic", type: "pattern", weight: 0.8, planetarySource: "Venus", originType: .natal))
            default:
                tokens.append(StyleToken(name: "balanced", type: "pattern", weight: 0.8, planetarySource: "Venus", originType: .natal))
            }
            
            // Modality pattern additions
            switch venusModality {
            case "cardinal":
                tokens.append(StyleToken(name: "directional", type: "pattern", weight: 0.7, planetarySource: "Venus", originType: .natal))
            case "fixed":
                tokens.append(StyleToken(name: "symmetrical", type: "pattern", weight: 0.8, planetarySource: "Venus", originType: .natal))
            case "mutable":
                tokens.append(StyleToken(name: "irregular", type: "pattern", weight: 0.6, planetarySource: "Venus", originType: .natal))
            default:
                break
            }
        }
        
        // Mercury pattern communication
        if let mercury = chart.planets.first(where: { $0.name == "Mercury" }) {
            let mercuryElement = getSignElement(sign: mercury.zodiacSign)
            switch mercuryElement {
            case "fire", "air":
                tokens.append(StyleToken(name: "communicative", type: "pattern", weight: 0.6, planetarySource: "Mercury", originType: .natal))
            case "earth", "water":
                tokens.append(StyleToken(name: "subtle", type: "pattern", weight: 0.5, planetarySource: "Mercury", originType: .natal))
            default:
                break
            }
        }
        
        return tokens
    }
    
    /// Generate accessory tokens based on planetary influences
    static func generateAccessoryTokens(chart: NatalChartCalculator.NatalChart) -> [StyleToken] {
        var tokens: [StyleToken] = []
        
        // Venus accessory preferences
        if let venus = chart.planets.first(where: { $0.name == "Venus" }) {
            let venusElement = getSignElement(sign: venus.zodiacSign)
            
            switch venusElement {
            case "fire":
                tokens.append(StyleToken(name: "eye-catching", type: "accessory", weight: 1.0, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "dramatic", type: "accessory", weight: 0.8, planetarySource: "Venus", originType: .natal))
            case "earth":
                tokens.append(StyleToken(name: "grounding", type: "accessory", weight: 1.1, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "substantial", type: "accessory", weight: 0.9, planetarySource: "Venus", originType: .natal))
            case "air":
                tokens.append(StyleToken(name: "conversational", type: "accessory", weight: 0.9, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "versatile", type: "accessory", weight: 0.7, planetarySource: "Venus", originType: .natal))
            case "water":
                tokens.append(StyleToken(name: "romantic", type: "accessory", weight: 1.0, planetarySource: "Venus", originType: .natal))
                tokens.append(StyleToken(name: "nostalgic", type: "accessory", weight: 0.8, planetarySource: "Venus", originType: .natal))
            default:
                tokens.append(StyleToken(name: "personal", type: "accessory", weight: 0.8, planetarySource: "Venus", originType: .natal))
            }
        }
        
        // Mars energy accessories
        if let mars = chart.planets.first(where: { $0.name == "Mars" }) {
            let marsElement = getSignElement(sign: mars.zodiacSign)
            
            switch marsElement {
            case "fire":
                tokens.append(StyleToken(name: "bold", type: "accessory", weight: 0.8, planetarySource: "Mars", originType: .natal))
            case "earth":
                tokens.append(StyleToken(name: "functional", type: "accessory", weight: 0.7, planetarySource: "Mars", originType: .natal))
            case "air":
                tokens.append(StyleToken(name: "expressive", type: "accessory", weight: 0.6, planetarySource: "Mars", originType: .natal))
            case "water":
                tokens.append(StyleToken(name: "protective", type: "accessory", weight: 0.7, planetarySource: "Mars", originType: .natal))
            default:
                break
            }
        }
        
        // Jupiter expansion accessories
        if chart.planets.contains(where: { $0.name == "Jupiter" }) {
            tokens.append(StyleToken(name: "generous", type: "accessory", weight: 0.5, planetarySource: "Jupiter", originType: .natal))
        }
        
        return tokens
    }
    
    // Helper methods for elemental and modal analysis
    // Contract: sign is 1-based (Aries=1 … Pisces=12).
    // Fire={1,5,9}, Earth={2,6,10}, Air={3,7,11}, Water={4,8,12}
    static func getSignElement(sign: Int) -> String {
        let elements = ["fire", "earth", "air", "water"]
        guard (1...12).contains(sign) else { return "fire" }
        return elements[(sign - 1) % 4]
    }

    // Cardinal={1,4,7,10}, Fixed={2,5,8,11}, Mutable={3,6,9,12}
    static func getSignModality(sign: Int) -> String {
        let modalities = ["cardinal", "fixed", "mutable"]
        guard (1...12).contains(sign) else { return "cardinal" }
        return modalities[(sign - 1) % 3]
    }
    
    private static func calculateElementalWeights(chart: NatalChartCalculator.NatalChart) -> [String: Double] {
        var weights: [String: Double] = ["fire": 0, "earth": 0, "air": 0, "water": 0]
        
        for planet in chart.planets {
            let element = getSignElement(sign: planet.zodiacSign)
            let planetWeight: Double
            
            switch planet.name {
            case "Sun": planetWeight = 2.0
            case "Moon": planetWeight = 2.0
            case "Venus": planetWeight = 1.8
            case "Mars": planetWeight = 1.5
            case "Mercury": planetWeight = 1.2
            default: planetWeight = 1.0
            }
            
            weights[element, default: 0] += planetWeight
        }
        
        return weights
    }
}
